enum DiscoveryHelpTargetId {
  helpButton,
  coverPage,
  startDiscoveringButton,
  feedView,
  searchBar,
  sortByLocationButton,
  andMoreButton,
  sourceActionButton,
  shareActionButton,
  locationActionButton,
  saveActionButton,
  moreActionButton,
  discoveryActions,
}
