enum PublicProfileHelpTargetId {
  helpButton,
  profileHeader,
  followingFollowersCount,
  bioText,
  shareButton,
  collectionsTabSwitch,
  reviewsTabSwitch,
  currentView,
  followButton,
  mapButton,
  categoryToggleButton,
  collectionCategoryItem,
  collectionExperienceItem,
  collectionReviewItem,
}
